version: "3.3"
services:
  app-front:
    build: '.'
    container_name: app-front
    ports:
      - 80:80
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: app-network
